FORMAT: 1A
HOST: prodetotal-ziggurat.rhcloud.com

# prodetotal
Prode Total

## Competitions [/competitions]
### List all Competitions [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "exact_match_points": 6,
            "result_match_points": 3,
            "no_match_points": 0,
            "no_forecast_points": 0,
            "name": "Copa del Mundo Brasil 2014",
            "start_date": "2014-03-31",
            "end_date": "2014-03-31",
            "created_at": "2014-03-31T23:35:40.444Z",
            "updated_at": "2014-03-31T23:35:40.444Z"
          },
          {
            "id": 2,
            "exact_match_points": 6,
            "result_match_points": 3,
            "no_match_points": 0,
            "no_forecast_points": 0,
            "name": "Champions League 2014",
            "start_date": "2014-03-31",
            "end_date": "2014-03-31",
            "created_at": "2014-04-01T00:32:24.781Z",
            "updated_at": "2014-04-01T00:32:24.781Z"
          }
        ]

### Create a Competition [POST]
+ Request (application/json)

        {    
            "exact_match_points": 6,
            "result_match_points": 3,
            "no_match_points": 0,
            "no_forecast_points": 0,
            "name": "Copa del Mundo Brasil 2014",
            "start_date": "2014-03-31T19:27:42.242Z",
            "end_date": "2014-03-31T19:27:42.242Z"
        }

+ Response 201 (application/json)

        {
          "id": 3,
          "exact_match_points": 6,
          "result_match_points": 3,
          "no_match_points": 0,
          "no_forecast_points": 0,
          "name": "Copa del Mundo Brasil 2014",
          "start_date": "2014-03-31",
          "end_date": "2014-03-31",
          "created_at": "2014-04-01T00:33:32.615Z",
          "updated_at": "2014-04-01T00:33:32.615Z"
        }
